export type Permissions = {
  grants?: RolePermissionGrants;
  spans?: RolePermissionSpans;
};

export type RolePermissionSpanType = keyof (typeof spanTypeMap);

const spanTypeMap = {
  SE: true,
  RE: true,
  AE: true,
  DE: true,
  LO: true,
  CO: true,
  RS: true,
  CL: true,
  SP: true,
};

type RolePermissionSpan = { [key: string]: RolePermissionSpanValue };
type RolePermissionSpanValue = number[];
type RolePermissionSpans = { [F in RolePermissionSpanType]?: RolePermissionSpan };

type RolePermissionGrants = { [RPG in RolePermissionGrant]?: RolePermissionGrantValue[] | null };
type RolePermissionGrantValue = [string, number];
export type RolePermissionGrant = keyof (typeof permissionsMap);

// see // see yourPeople3/zenefits_hub/auth/roles_permissions/constants.py
const permissionsMap = {
  can_add_remove_admins: true,
  administer_employee_edit_basic_info: true,
  admin_edit_employee_payroll_data: true,
  administer_employee_edit_sensitive_info: true,
  administer_employee_view_basic_info: true,
  administer_employee_view_sensitive_info: true,
  is_benefits_admin: true,
  is_benefits_analyst: true,
  is_benefits_broker: true,
  is_benefits_broker_partner_admin: true,
  'ben_admin:employee_benefits_contact': true,
  'ben_admin:fulfillment_contact': true,
  is_benefits_fulfillment_manager: true,
  is_benefits_renewals_manager: true,
  can_approve_pto: true,
  can_approve_tapp: true,
  can_approve_tappe: true,
  can_change_tae_approver: true,
  can_complete_i9: true,
  can_create_project_codes: true,
  can_create_tk_admin: true,
  can_edit_tae_settings: true,
  can_edit_timesheet: true,
  can_enroll_tac: true,
  can_lock_tapp: true,
  can_push_tapp: true,
  can_read_company_holiday_calendar: true,
  can_read_duration_note: true,
  can_read_ee_duration: true,
  can_read_ee_duration_flag: true,
  read_ee_pto_account: true,
  can_read_ee_pto_liability: true,
  read_ee_pto_policy: true,
  can_read_ee_pto_request: true,
  can_read_ee_time_approved_day: true,
  read_employer_pto_account: true,
  read_employer_pto_policy: true,
  can_read_project_code: true,
  can_read_ta_company: true,
  can_read_tae: true,
  can_read_tapp: true,
  can_read_tapp_run: true,
  can_read_tappe: true,
  can_read_tk_admins: true,
  can_receive_hr_emails: true,
  can_request_employee_calendar_feed: true,
  can_request_pto: true,
  can_run_ee_pto_report: true,
  CAN_RUN_TA_DATA_REPORTS: true,
  can_run_ta_reports: true,
  can_run_tapp_report: true,
  can_setup_pto_policy: true,
  can_setup_tac: true,
  can_view_pay_run: true,
  can_view_sensitive_pto_data: true,
  can_view_ta_overview: true,
  can_view_timesheet: true,
  can_write_company_holiday_calendar: true,
  can_write_duration_note: true,
  can_write_ee_duration: true,
  can_write_ee_duration_flag: true,
  write_ee_pto_account: true,
  write_ee_pto_policy: true,
  write_ee_pto_request: true,
  can_write_ee_time_approved_day: true,
  write_employer_pto_account: true,
  write_employer_pto_policy: true,
  can_write_project_code: true,
  can_write_ta_company: true,
  can_write_ee_tae: true,
  can_write_tapp: true,
  can_write_tappe: true,
  is_admin: true,
  is_contractor_admin: true,
  download_benefits_reports: true,
  manage_company_profile: true,
  edit_employee_benefits_data: true,
  edit_fulfillment_task: true,
  edit_group_benefits_data: true,
  edit_partner_user: true,
  is_full_company_admin: true,
  handle_aca_benefits: true,
  handle_benefits_deductions: true,
  handle_cobra_benefits: true,
  is_hr_admin: true,
  is_main_admin: true,
  manage_employee_edit_basic_info: true,
  manage_requested_reports: true,
  manage_employee_view_basic_info: true,
  is_partner_account: true,
  is_payroll_admin: true,
  'platform:add_remove_apps': true,
  'platform:admin': true,
  'platform:get_private_access_token': true,
  is_pto_admin: true,
  'public_api:banks': true,
  'public_api:companies': true,
  'public_api:companies.ein': true,
  'public_api:companies.legal_address': true,
  'public_api:companies.legal_name': true,
  'public_api:company_banks': true,
  'public_api:departments': true,
  'public_api:employments': true,
  'public_api:employments.compensation': true,
  'public_api:employments.employment_type': true,
  'public_api:employments.termination_type': true,
  'public_api:flex_contributions': true,
  'public_api:journals': true,
  'public_api:locations': true,
  'public_api:new_hire': true,
  'public_api:openid': true,
  'public_api:payroll_person_information': true,
  'public_api:paystubs': true,
  'public_api:paystubs.deduction_items.401k': true,
  'public_api:paystubs.deduction_items.dental': true,
  'public_api:paystubs.deduction_items.medical': true,
  'public_api:paystubs.deduction_items.vision': true,
  'public_api:paystubs.earning_items.other': true,
  'public_api:paystubs.earning_items.salary': true,
  'public_api:paystubs.pay_schedule': true,
  'public_api:paystubs.summary.deductions': true,
  'public_api:paystubs.summary.employee_tax': true,
  'public_api:paystubs.summary.employer_tax': true,
  'public_api:paystubs.summary.gross': true,
  'public_api:paystubs.summary.hours': true,
  'public_api:paystubs.summary.net': true,
  'public_api:paystubs.tax_items.federal': true,
  'public_api:paystubs.tax_items.medicare': true,
  'public_api:paystubs.tax_items.social_security': true,
  'public_api:paystubs.tax_items.state': true,
  'public_api:people': true,
  'public_api:people.date_of_birth': true,
  'public_api:people.department': true,
  'public_api:employees.federal_filing_status': true,
  'public_api:employees.gender': true,
  'public_api:people.home_address': true,
  'public_api:people.location': true,
  'public_api:people.manager': true,
  'public_api:people.personal_email': true,
  'public_api:people.personal_phone': true,
  'public_api:people.photo': true,
  'public_api:employees.social_security_number': true,
  'public_api:people.people.status': true,
  'public_api:people.work_email': true,
  'public_api:people.work_phone': true,
  'public_api:people.write_work_email': true,
  'public_api:platform': true,
  'public_api:platform_reserved_fields': true,
  'public_api:slackbot': true,
  'public_api:vacation_requests': true,
  'public_api:vacation_types': true,
  receive_fulfillment_task_notifications: true,
  review_employee_benefits_documents: true,
  setup_benefits: true,
  is_time_and_attendance_admin: true,
  is_time_admin: true,
  is_tk_admin: true,
  trigger_benefits_notifications: true,
  trigger_benefits_renewals: true,
  view_company_profile: true,
  view_employee_benefits_data: true,
  view_employee_compensation: true,
  view_fulfillment_task: true,
  view_group_benefits_data: true,
  view_partner_user: true,
  'flow:administration': true,
  'flow:management': true,
  'flow:self_service': true,
};
